version: "3.3"

services:
  ghorde_surreal:
    image: surrealdb/surrealdb:latest
    container_name: ghorde_surrealdb
    restart: always
    command: start --user root --pass root file:/data/database.db
    ports:
      - 8000:8000
    volumes:
      - ./data:/data
  ghorde_bot:
    container_name: ghorde_bot
    build: 
      context: ./
      dockerfile: dockerfile.bot
    volumes: 
      - ./ghorde-bot:/app