version: "3.3"

services:
  ghorde-surreal-prod:
    image: surrealdb/surrealdb:latest
    container_name: ghorde-surreal-prod
    restart: always
    command: start --user root --pass root file:/data/database.db
    ports:
      - 8000:8000
    volumes:
      - ./data:/data
  ghorde-api-prod:
    container_name: ghorde-api-prod
    build:
      context: ./
      dockerfile: dockerfile.prod.api
    ports:
      - 5050:5050
    depends_on: 
      - ghorde-surreal-prod
    restart: always
    environment:
      - PORT=5050
      - SURREAL_LOC=http://ghorde-surreal-prod:8000/rpc 
      - SURREAL_USER=root
      - SURREAL_PASS=root
      - LOGGER_LEVEL=info
      - ORIGINS=https://ghorde.kodski.com,http://ghorde-bot-prod
  ghorde-bot-prod:
    container_name: ghorde-bot-prod
    build: 
      context: ./
      dockerfile: dockerfile.prod.bot
    restart: always
    environment:
      - LOGGER_LEVEL=info
      - DEFAULT_PREFIX=!
      - API_LOC=http://ghorde-api-prod:5050/bot
    depends_on: 
      - ghorde-api-prod